### ISSUE TITLE
Exception handling error.

### ISSUE THREAD

**Issue by Alex29954** [Alex29954/Bloxer#7]
I am making `RectangleButton` and want to draw text on top of this button.
I decided to use `sf::Text` to draw on screen, but to set text I need to set `sf::Font` for font and `sf::String` for string to `sf::Text`.
When I try to set `sf::Font` and `sf::String` I get an **exception error**.
Check **RectangleButton.h**, **RectangleButton.cpp** and **Bloxer::GameManager::run()**
 method for code in `Rectangle_Button_Text` branch.

Can you help me please to solve this?

**Comment by Alex29954** [comment]
It's `Alex` branch by the way.

**Comment by CeytiX** [comment]
In which file (and which lines) do you try to set sf::Font and sf::String ?

**Comment by Alex29954** [comment]
@CeytiX `RectangleButton.cpp`, line 6, branch **Rectangle_Button_Text**.

**Comment by CeytiX** [comment]
I don't find any exception error but why don't you write

    : m_button_pos   (pos_x, pos_y)
    , m_button_size  (width, height)
    , m_button_string = string // (string) -> = string
?

**Comment by Alex29954** [comment]
Where have you found this?

**Comment by Alex29954** [comment]
Here where the problem is: https://github.com/Alex29954/Bloxer/blob/Rectangle_Button_Text/Source-Files/RectangleButton.cpp

**Comment by CeytiX** [comment]
lines 4-6
